spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: auth_ms

  flyway:
    enabled: true
    schemas: auth_ms
    default-schema: auth_ms
    locations: classpath:db/migration,classpath:db/seeds
    baseline-on-migrate: true

eureka:
  instance:
    hostname: ${HOSTNAME:auth-service}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: false

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
  resend:
    api-key: ${APP_RESEND_API_KEY}
    from: ${APP_RESEND_FROM:noreply@enfoca.online}
    frontend-url: ${APP_RESEND_FRONTEND_URL:https://enfoca.online}

management:
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    diskSpace:
      enabled: true
    db:
      enabled: true

logging:
  level:
    root: WARN
    online.enfoca: INFO
