spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  instance:
    hostname: ${HOSTNAME:auth-service}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: false

app:
  jwt:
    secret: ${JWT_SECRET_KEY}

management:
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    diskSpace:
      enabled: true
    db:
      enabled: true

logging:
  level:
    root: WARN
    online.enfoca: INFO
