spring:
  application:
    name: auth-service

  profiles:
    active: local

  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop

  autoconfigure:
    exclude:
      - org.springframework.boot.amqp.autoconfigure.RabbitAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.RedisAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.RedisReactiveAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5434/enfoca_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Kaoz1699}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: auth
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
    issuer: enfoca

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    diskSpace:
      enabled: true
    db:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
