spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    out-of-order: true
    locations: classpath:db/migration,classpath:db/seeds

app:
  jwt:
    secret: dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHk=
  resend:
    api-key: re_HU3kVQNn_Kz4B4yrGfNTHe4Gewn3yUsta
    from: noreply@enfoca.online
    frontend-url: http://localhost:5173

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:8081
    status-page-url: http://localhost:8081/actuator/info
    health-check-url: http://localhost:8081/actuator/health
    home-page-url: http://localhost:8081/

logging:
  level:
    online.enfoca.authservice: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG
