spring:
  application:
    name: discovery-service
  profiles:
    active: local
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.MongoAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.MongoDataAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.RedisAutoConfiguration
      - org.springframework.boot.amqp.autoconfigure.RabbitAutoConfiguration

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
