eureka:
  instance:
    hostname: localhost

spring:
  data:
    redis:
      host: coherent-hagfish-108591.upstash.io
      port: 6379
      password: gQAAAAAAAagvAAIgcDI4MjdlYzI1YTM4NTY0YmM3OTFkNTU5MTg0NzZlZDMwMQ
      ssl:
        enabled: true
